### PR TITLE
new misc driver interface for amlogic cec

### PR DESCRIPTION
**Pull request by gdachs**
@codesnake: now as a pull request

### CODE REVIEW

**Comment by codesnake** [comment]
Unfortunately I checked and it doesn't work well. CEC stops working after a while. Original author of the patch also mentions this problem: http://forum.odroid.com/viewtopic.php?f=111&t=7540&start=150#p79142. See p9.

**Comment by gdachs** [comment]
Yes, but it is not the fault of the patch. The patch helps to investigate it.

**Comment by codesnake** [comment]
Amlogics HDMI CEC implementation works without problems for me.

**Comment by gdachs** [comment]
We discussed this already. What is working? I can't see how I am able to power on TV/AVR with Amlogics HDMI CEC implementation. Can you show me how?

**Comment by codesnake** [comment]
With your patch even button presses on TVs remote don't work.

**Comment by codesnake** [comment]
And after applying you patch Kodi sometimes hangs on splash screen during a boot.

**Comment by gdachs** [comment]
Without the patch only the remote is working. I have thought it is better to find an error in existing code, instead of living with missing functionality, but of course you are free not to use the patch.

**Comment by codesnake** [comment]
Yes, I agree that Amlogics HDMI CEC implementation has a lot of problems, but your implementation currently works even worse. People use HDMI CEC not to only turn on/off the TV. Believe me I don't have nothing against you patch, but in current state it is not usable. I'll be glad to merge the PR after the issues will be fixed.

**Comment by gdachs** [comment]
I am not a kernel hacker and have not enough time to do that, we should stop this now. Sorry for wasting your time. Had hoped it would be a faster solution for the problem.

**Comment by codesnake** [comment]
I struggled with your patch for a whole day, hoping to find a solution for the problem. But unfortunately currently I don't have an idea why it doesn't work.

**Comment by gdachs** [comment]
thanks for trying!

**Comment by codesnake** [comment]
np. you are welcome.

**Comment by Hedda** [comment]
@codesnake @gdachs optimally CEC should really not even be implemented into the Linux kernel at all, but userspace instead. see discussion with opdenkamp (libcec author) comments about LibCEC and the "HDMI CEC framework" for the Linux kernel here: 

https://github.com/Pulse-Eight/libcec/issues/67

However if they insist that it is implement into the Linux kernel then the suggested "HDMI CEC framework" might be better than previous implementations.

http://lists.freedesktop.org/archives/dri-devel/2015-March/079678.html

http://lists.freedesktop.org/archives/dri-devel/2015-March/thread.html#79678

**Pull request closed without merging**
