### PR TITLE
[aml/meson6]- apply 1080p24@48khz audiomode fix from meson8 - fixes audi...

### PR DESCRIPTION
**Pull request by Memphiz**
...o locking issue for yamaha amps with this video mode

### CODE REVIEW

**Comment by Memphiz** [comment]
this might need some more tweaks for 44k1 and 96k modes on 1080p24 ... will update the pr as soon as i found the key...

**Comment by Memphiz** [comment]
ok i expanded that fix for all samplerates - tested it with 44k1, 48k and 96k (thats all my amp can do) - basically we need 3 times the n value for the 24hz mode.

**Comment by codesnake** [comment]
Thanks!

**Comment by codesnake** [comment]
Sorry, clicked wrong button :)

**Pull request merged**
